version: '1'
services:
  postgresql:
    image: postgres:11.6
    environment:
      POSTGRES_DB: pulsesurveydb
      POSTGRES_USER: pulsesurvey
      POSTGRES_PASSWORD: pulsesurveypass
    volumes:
      - ./server/src/main/resources/db/2019.12.18.14.06.00_createInitialDb.sql:/docker-entrypoint-initdb.d/2019.12.18.14.06.00_createInitialDb.sql
